[common]
application.modules = "Index,Home,Api,Admin,Adminv2,Merchant,Script,Transit"
application.dispatcher.defaultModule = 'Index'
application.dispatcher.defaultController = 'Index'
application.library.namespace = "App"
application.dispatcher.throwException=1
application.dispatcher.catchException=1
application.directory = APP_PATH "/application"
application.bootstrap = APP_PATH "/application/bootstrap/Bootstrap.php"
;application.view.ext = phtml
application.debug = true
storage.directory = APP_PATH "/storage"

;user
user.default_filter='trim,addslashes,htmlspecialchars'
user.password.salt = 'Lh5$Jf4MWVD!'
user.uuid.salt = '2gQg*o@sPUq7'

encrypt.encrypt_key = asICLVMeQmR04PzZs7j6e2qnMqgp2G8m
encrypt.sign_key = EgZxVCKTqgrmZzF7I3O6C8TWDmogpiXp
encrypt.token_key = z2iTT2nx4oXxEk60yUWKCT3wUu9CNh0j


system.name = 51tt
system.uploadKeyOld = 
system.uploadKeyNew = 
system.uploadKeyCut = 

sms.url =

;mv notify 切片回调
mv.notify.token = 8450574803:AAEidmnxViIQovXNFikpwCMIJQaQs0cmfAw
mv.notify.url = https://api.telegram.org/bot
mv.notify.slice.chat_id = -1003134980529
; img
img.backend.book.url=

video.encrypt.api = 
video.encrypt.referer = 
video.encrypt.m3u8 = 

; upload
upload.img_upload=

;普通移动端小于100m文件上传
upload.mobile.mp4_upload=
;web 创作中心大文件上传
upload.mp4_upload=
upload.mp4.key=
upload.img.key=

;im
im.upload.url=
im.base.url=

; pay //生成付款地址及签名key
;pay.pay_url=http://payments.hyys.info/v1/payments
pay.pay_url=
pay.app_name=911cgw
;支付回调
pay.notify=
;提现通过-处理
withdraw.url=
;提现回调
withdraw.notify=

;线路检测
;line.url=https://bpi1.rxzwhkb.com/api.php,https://bpi1.obmarrq.com/api.php,https://bpi1.zqmgaxe.com/api.php
line.url=
line.pwa_url=
github.url=

smarty.left_delimiter='{%'
smarty.right_delimiter='%}'
smarty.template_dir=APP_PATH'/application/modules/Admin/views/'
smarty.compile_dir=APP_PATH'/application/modules/Admin/cache/compile'
smarty.cache_dir=APP_PATH'/application/modules/Admin/cache/'

; 用于生成上传图片的完整访问地址
backend.base_url = https://911cg.dyclub.co

admin.site_url = https://gd-staff.gdcm01.com/

;客服茶小儿配置
kf.uuid=
kf.agent=


#小说解密KEY与IV
story.key=
story.iv=
story.visit=
story.upload=

# mp4处理
mp4.accept=http://examine-new.xmyy8.co/queue.php
mp4.destroy=
mp4.notify_url = https://911cg.net/

pay.pay_signkey=
withdraw.key=

# 联盟id
union.pid=41
# 调试
union.log_level=9
# 联盟加解密key
union.key=
# 联盟签名key
union.sign=
# 联盟消息存放在redis中的消息队列name
union.qname=
#yaf缓存 前缀
yaf.prefix=911cgw

;广告中心配置全部配置
;//请求base链接 测试环境 https://adopenapi.adcs01.top
adscenter.base_uri='https://adopenapi.adcs01.top'
;//业务后台-同步广告中心数据
adscenter.sync2center_url='https://adadmin.adcs01.top/api/advertise/sync/syncAdData'
;//密钥
adscenter.decrypt_key='go+1Yi4UqMhV/XVC6ru+TUaNelh29tRygCjgzUkYI+U'
;//商户编号
adscenter.merchan_code='1991015570819227648'
;//部门编号
adscenter.department_code='1990985731052380160'
;//应用编号
adscenter.app_code='TJ-060'
;//客户编号 暂时可空
adscenter.customer_code='1991016060940427264'
[product : common]
[test : common]
[develop : common]
[dev : common]