[common]

;redis
redis.host=127.0.0.1
redis.prefix=gdcm:

database.driver='mysql'
database.read.host='127.0.0.1'
database.write.host='127.0.0.1'
database.port='3306'
database.database='gdapi'
database.username='root'
database.password='pArm*%anEntF]'
database.charset='utf8'
database.collation='utf8_unicode_ci'
database.prefix='sq_'
database.strict=false

; im数据库
im.driver = "mysql"
im.read.host = "192.168.172.194"
im.write.host = "192.168.172.194"
im.port = "3306"
im.database = "im_duoshan"
im.username = "im"
im.password = "Ufzy=9(kfSs<"
im.charset = "utf8"
im.collation = "utf8_unicode_ci"
im.prefix = "im_"
im.strict = false

; 漫画数据库
mhsync.driver = "mysql"
mhsync.read.host = "192.168.163.3"
mhsync.write.host = "192.168.163.3"
mhsync.port = "3306"
mhsync.database = "down_dm"
mhsync.username = "resource_sync"
mhsync.password = "kJ@6p0PK!Ocf5Lkw"
mhsync.charset = "utf8"
mhsync.collation = "utf8_unicode_ci"
mhsync.prefix = "wyw_"
mhsync.strict = false


; 汤不热数据库
tbr.driver = "mysql"
tbr.read.host = "45.118.134.78"
tbr.write.host = "45.118.134.78"
tbr.port = "3306"
tbr.database = "t_bure"
tbr.username = "resource_sync"
tbr.password = "Ufzy=9(kfSs<sdf"
tbr.charset = "utf8"
tbr.collation = "utf8_unicode_ci"
tbr.prefix = "tbr_"
tbr.strict = false



[product : common]
[test : common]
[develop : common]


