server {
    listen       ${NGINX_V4_PORT} ${NGINX_DEF};
    listen       ${NGINX_V6_PORT} ${NGINX_DEF};
    server_name  ${SLUG_API};
    root   ${DEPLOY_PATH}/public/api;

    index api.php;
    location / {
        try_files $uri $uri/ /api.php$is_args$args;
        if (!-e $request_filename) {
            rewrite ^/(.*)  /api.php/$1 last;
        }
    }
    location ~ /\. { deny  all; }
    include enable-php-pathinfo.conf;
}