server {
    listen       ${NGINX_V4_PORT} ${NGINX_DEF};
    listen       ${NGINX_V6_PORT} ${NGINX_DEF};
    server_name  ${SLUG_NAV};
    root   ${DEPLOY_PATH}/public/nav;

    index t.php;
    location / {
        try_files $uri $uri/ /t.php?$is_args$args;
    }
    if ($http_user_agent ~* (Amazonbot|SemrushBot|GPTBot|ClaudeBot)) {
        return 403;
    }
    location ~ /\. { deny  all; }
    include enable-php-pathinfo.conf;
}
