server {
    listen       ${NGINX_V4_PORT} ${NGINX_DEF};
    listen       ${NGINX_V6_PORT} ${NGINX_DEF};
    server_name  ${SLUG_STAFF};
    root   ${DEPLOY_PATH}/public/staff;

    index d.php;
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
        if (!-e $request_filename) {
            rewrite ^/(.*)  /d.php/$1 last;
        }
    }
    location /internal_cache/ {
        internal;
        etag off;
        add_header ETag $upstream_http_etag;
        add_header Last-Modified $upstream_http_last_modified;
        alias ${DEPLOY_PATH}/storage/internal_cache/;
        sendfile on;
        tcp_nopush on;
    }
    if ($http_user_agent ~* (Amazonbot|SemrushBot|GPTBot|ClaudeBot)) {
        return 403;
    }
    location ~ /\. { deny  all; }
    include enable-php-pathinfo.conf;
}
